name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3', '8.4']
        dependencies:
          - "lowest"
          - "highest"
      fail-fast: false
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0

    - name: Install PHP
      uses: shivammathur/setup-php@20529878ed81ef8e78ddf08b480401e6101a850f # 2.35.3
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, dom, igbinary

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: "Composer install ${{ matrix.dependencies }} dependencies"
      uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # 3.1.1
      with:
        dependency-versions: "${{ matrix.dependencies }}"
      env:
        COMPOSER_PROCESS_TIMEOUT: 6000

    - name: Run test suite
      run: composer run-script test
