name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
    steps:
    - uses: actions/checkout@v1
    
    - name: Install PHP
      uses: shivammathur/setup-php@1.7.0
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, dom

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: composer run-script test
